# Generated by Django 5.2.8 on 2025-11-28 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_example',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('authorityid', models.AutoField(db_column='authorityID', primary_key=True, serialize=False)),
                ('departmentname', models.CharField(blank=True, db_column='departmentName', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('houseno', models.CharField(blank=True, db_column='houseNo', max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('thana', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('assignedarea', models.CharField(blank=True, db_column='assignedArea', max_length=100, null=True)),
                ('profilecertificate', models.CharField(blank=True, db_column='profileCertificate', max_length=255, null=True)),
                ('datejoined', models.DateField(blank=True, db_column='dateJoined', null=True)),
            ],
            options={
                'db_table': 'Authority',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('communityid', models.AutoField(db_column='communityID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('thana', models.CharField(max_length=50)),
                ('postalcode', models.CharField(db_column='postalCode', max_length=20)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Community',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('residentid', models.AutoField(db_column='residentID', primary_key=True, serialize=False)),
                ('house_no', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('thana', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=8, null=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Resident',
            },
        ),
        migrations.CreateModel(
            name='Serviceprovider',
            fields=[
                ('providerid', models.AutoField(db_column='providerID', primary_key=True, serialize=False)),
                ('service_area', models.CharField(blank=True, max_length=100, null=True)),
                ('workinghours', models.CharField(blank=True, db_column='workingHours', max_length=50, null=True)),
                ('certificationfile', models.CharField(blank=True, db_column='certificationFile', max_length=255, null=True)),
                ('availability_status', models.CharField(blank=True, max_length=9, null=True)),
                ('subrole', models.CharField(blank=True, db_column='subRole', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ServiceProvider',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.AutoField(db_column='bookingID', primary_key=True, serialize=False)),
                ('bookingdate', models.DateField(db_column='bookingDate')),
                ('servicedate', models.DateField(db_column='serviceDate')),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentstatus', models.CharField(blank=True, db_column='paymentStatus', max_length=8, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('communityid', models.ForeignKey(db_column='communityID', on_delete=django.db.models.deletion.CASCADE, to='base.community')),
                ('residentid', models.ForeignKey(db_column='residentID', on_delete=django.db.models.deletion.CASCADE, to='base.resident')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Issuereport',
            fields=[
                ('issueid', models.AutoField(db_column='issueID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('mapaddress', models.CharField(blank=True, db_column='mapAddress', max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=11, null=True)),
                ('prioritylevel', models.CharField(blank=True, db_column='priorityLevel', max_length=6, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('resolvedat', models.DateTimeField(blank=True, db_column='resolvedAt', null=True)),
                ('communityid', models.ForeignKey(db_column='communityID', on_delete=django.db.models.deletion.CASCADE, to='base.community')),
                ('residentid', models.ForeignKey(db_column='residentID', on_delete=django.db.models.deletion.CASCADE, to='base.resident')),
            ],
            options={
                'db_table': 'IssueReport',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(db_column='paymentID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=5)),
                ('transactionid', models.CharField(blank=True, db_column='transactionID', max_length=100, null=True)),
                ('paymentdate', models.DateTimeField(auto_now_add=True, db_column='paymentDate')),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('bookingid', models.OneToOneField(db_column='bookingID', on_delete=django.db.models.deletion.CASCADE, to='base.booking')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Emergencyreport',
            fields=[
                ('sosid', models.AutoField(db_column='sosID', primary_key=True, serialize=False)),
                ('emergencytype', models.CharField(db_column='emergencyType', max_length=8)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('communityid', models.ForeignKey(db_column='communityID', on_delete=django.db.models.deletion.CASCADE, to='base.community')),
                ('residentid', models.ForeignKey(db_column='residentID', on_delete=django.db.models.deletion.CASCADE, to='base.resident')),
            ],
            options={
                'db_table': 'EmergencyReport',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.AutoField(db_column='serviceID', primary_key=True, serialize=False)),
                ('servicename', models.CharField(db_column='serviceName', max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('communityid', models.ForeignKey(db_column='communityID', on_delete=django.db.models.deletion.CASCADE, to='base.community')),
                ('providerid', models.ForeignKey(db_column='providerID', on_delete=django.db.models.deletion.CASCADE, to='base.serviceprovider')),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='serviceid',
            field=models.ForeignKey(db_column='serviceID', on_delete=django.db.models.deletion.CASCADE, to='base.service'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(db_column='reviewID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('bookingid', models.OneToOneField(db_column='bookingID', on_delete=django.db.models.deletion.CASCADE, to='base.booking')),
                ('residentid', models.ForeignKey(db_column='residentID', on_delete=django.db.models.deletion.CASCADE, to='base.resident')),
                ('providerid', models.ForeignKey(db_column='providerID', on_delete=django.db.models.deletion.CASCADE, to='base.serviceprovider')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Issueassignment',
            fields=[
                ('assignmentid', models.AutoField(db_column='assignmentID', primary_key=True, serialize=False)),
                ('assigneddate', models.DateTimeField(auto_now_add=True, db_column='assignedDate')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('authorityid', models.ForeignKey(db_column='authorityID', on_delete=django.db.models.deletion.CASCADE, to='base.authority')),
                ('issueid', models.ForeignKey(db_column='issueID', on_delete=django.db.models.deletion.CASCADE, to='base.issuereport')),
                ('providerid', models.ForeignKey(blank=True, db_column='providerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.serviceprovider')),
            ],
            options={
                'db_table': 'IssueAssignment',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='providerid',
            field=models.ForeignKey(db_column='providerID', on_delete=django.db.models.deletion.CASCADE, to='base.serviceprovider'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, db_column='date_Of_birth', null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('twofactorcode', models.CharField(blank=True, db_column='twoFactorCode', max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_profile', to=settings.AUTH_USER_MODEL)),
                ('communityid', models.ForeignKey(blank=True, db_column='communityID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.community')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='userid',
            field=models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AddField(
            model_name='resident',
            name='userid',
            field=models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(db_column='notificationID', primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=7)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('isread', models.BooleanField(db_column='isRead', default=False)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('communityid', models.ForeignKey(blank=True, db_column='communityID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.community')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Loginlog',
            fields=[
                ('logid', models.AutoField(db_column='logID', primary_key=True, serialize=False)),
                ('user_role', models.CharField(blank=True, max_length=15, null=True)),
                ('logintime', models.DateTimeField(auto_now_add=True, db_column='loginTime')),
                ('logouttime', models.DateTimeField(blank=True, db_column='logoutTime', null=True)),
                ('ipaddress', models.CharField(blank=True, db_column='ipAddress', max_length=45, null=True)),
                ('deviceinfo', models.CharField(blank=True, db_column='deviceInfo', max_length=255, null=True)),
                ('twofactorstatus', models.CharField(blank=True, db_column='twoFactorStatus', max_length=7, null=True)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'LoginLog',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.AutoField(db_column='eventID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=8)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('communityid', models.ForeignKey(db_column='communityID', on_delete=django.db.models.deletion.CASCADE, to='base.community')),
                ('postedbyid', models.ForeignKey(db_column='postedByID', on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.AddField(
            model_name='authority',
            name='userid',
            field=models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.CreateModel(
            name='Activitylog',
            fields=[
                ('logid', models.AutoField(db_column='logID', primary_key=True, serialize=False)),
                ('actiontype', models.CharField(db_column='actionType', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('entityaffected', models.CharField(blank=True, db_column='entityAffected', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'ActivityLog',
            },
        ),
        migrations.CreateModel(
            name='Authoritycommunity',
            fields=[
                ('mapid', models.AutoField(db_column='mapID', primary_key=True, serialize=False)),
                ('authorityid', models.ForeignKey(db_column='authorityID', on_delete=django.db.models.deletion.CASCADE, to='base.authority')),
                ('communityid', models.ForeignKey(db_column='communityID', on_delete=django.db.models.deletion.CASCADE, to='base.community')),
            ],
            options={
                'db_table': 'AuthorityCommunity',
                'unique_together': {('authorityid', 'communityid')},
            },
        ),
        migrations.CreateModel(
            name='Issuevote',
            fields=[
                ('voteid', models.AutoField(db_column='voteID', primary_key=True, serialize=False)),
                ('votetype', models.CharField(db_column='voteType', max_length=8)),
                ('votedat', models.DateTimeField(auto_now_add=True, db_column='votedAt')),
                ('issueid', models.ForeignKey(db_column='issueID', on_delete=django.db.models.deletion.CASCADE, to='base.issuereport')),
                ('residentid', models.ForeignKey(db_column='residentID', on_delete=django.db.models.deletion.CASCADE, to='base.resident')),
            ],
            options={
                'db_table': 'IssueVote',
                'unique_together': {('issueid', 'residentid')},
            },
        ),
        migrations.CreateModel(
            name='Eventparticipation',
            fields=[
                ('participationid', models.AutoField(db_column='participationID', primary_key=True, serialize=False)),
                ('interesttype', models.CharField(db_column='interestType', max_length=10)),
                ('eventid', models.ForeignKey(db_column='eventID', on_delete=django.db.models.deletion.CASCADE, to='base.event')),
                ('residentid', models.ForeignKey(db_column='residentID', on_delete=django.db.models.deletion.CASCADE, to='base.resident')),
            ],
            options={
                'db_table': 'EventParticipation',
                'unique_together': {('eventid', 'residentid')},
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('emailid', models.AutoField(db_column='emailID', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'User_Email',
                'unique_together': {('userid', 'email')},
            },
        ),
        migrations.CreateModel(
            name='UserPhonenumber',
            fields=[
                ('phoneid', models.AutoField(db_column='phoneID', primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=20)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'User_PhoneNumber',
                'unique_together': {('userid', 'phonenumber')},
            },
        ),
    ]
