# Generated by Django 5.2.8 on 2025-11-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_user',
        ),
    ]
