# Generated by Django 5.2.8 on 2025-12-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_appuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
